<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $this->title; ?></title>
        <link id="themeStyles" rel="stylesheet" href="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/dojoroot/dijit/themes/tundra/tundra.css">
        <style type="text/css">
            @import "<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/dojoroot/dojo/resources/dojo.css";
            @import "<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/dojoroot/dojox/grid/resources/tundraGrid.css";
            @import "<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/dojoroot/dojox/layout/resources/FloatingPane.css";
            @import "<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/styles/importer.css";         
            @import "<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/styles/navigation.css";               
        </style>        
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/json2.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/utils.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/dojoroot/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/prototype-1.6.0.2.js"></script>
        
        <!-- custom application-level script files -->
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/application/importer/wizard.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/application/browserDetect.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/application/importer/utils.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/application/importer/navigation.js"></script>
        <script type="text/javascript" src="<?php echo App_Constants::PEN_WEB_ROOT; ?>/public/scripts/application/importer/metadata.js"></script>
        
        <script type="text/javascript">        
            dojo.require("dojo.parser");
            dojo.require("dojo.data.ItemFileWriteStore");
            dojo.require("dojox.grid.DataGrid");
            dojo.require("dojox.grid.cells");
            dojo.require("dijit.Dialog");
            dojo.require("dijit.form.TextBox");
            dojo.require("dijit.form.Button");
            dojo.require("dojox.layout.FloatingPane");            
            dojo.require("dijit.TitlePane");
            dojo.require("dijit.Tree");
            
            dojo.require("dijit.form.ComboBox");
            dojo.require("dijit.form.FilteringSelect");
            dojo.require("dojox.form.DropDownSelect");
            
            
            <?php echo $this->state; ?>
                       
            //include all of the functions that need to be called on startup:
            dojo.addOnLoad(function()
            {
                //alert("here");
                initMetadataPane();
                
                //hide initialization HTML until importer has completely loaded:
                dojo.byId('loaderInner').innerHTML += " done.";
                setTimeout(function hideLoader(){
                        var loader = dojo.byId('loader'); 
                        dojo.fadeOut({ node: loader, duration:500,
                                onEnd: function(){ 
                                        loader.style.display = "none"; 
                                }
                        }).play();
                }, 250);
            });
        </script>
    
    </head>
    <body class="tundra">
        <div id="loader"><div id="loaderInner">Loading Importer ... </div></div>
        <br />  
        
        <div>
            Name: <strong><span id="spanUserName"></span></strong><br />
            Project Selected: <strong><span id="spanProjectSelected"></span></strong> 
        </div>
        <table class="mainTable" align="center">
        <tr>
            <td colspan="2" class="headerCell">
                <?php echo $this->header; ?>
                <div id="errorMessage"></div>
            </td>
        </tr>
        <tr>
            <td class="navCell">
                <?php echo $this->sidebar; ?>
            </td>
            <td class="contentCell" id="contentCell">
                <?php echo $this->partial("wizardHeader.phtml") ?>
                <div style="height:350px; overflow:auto">
                    <table width="90%" align="center">
                        <tr>
                            <th style='width:150px'>Name:</th>
                            <td><input id='projName' type='text' name='projName' value=''/></td>
                        </tr>
                        <tr>
                            <th>Short Description:</th>
                            <td><textarea id='projSDes' rows='2' style='width:100%;' name='projSDes'></textarea></td>
                        </tr>
                        <tr>
                            <th>Long Description:</th>
                            <td><textarea id='projLDes' rows='10' style='width:100%;' name='projLDes'></textarea></td>
                        </tr>
                        <tr>
                            <th>Parent Context (Name):</th>
                            <td><input id='rootName' type='text' name='rootName' /></td>
                        </tr>
                        <tr>
                            <th>Parent Context (ID):</th>
                            <td><input id='rootID' type='text' name='rootID' /></td>
                        </tr>
                        <tr>
                            <th>Parent Context (Class):</th>
                            <td><input id='rootClass' type='text' name='rootClass' /></td>
                        </tr>
                        <tr>
                            <th>No Data Message:</th>
                            <td><textarea id='noData' rows='2' style='width:100%;' name='noData'></textarea></td>
                        </tr>
                        <tr>
                            <th>Creators (';' seperated):</th>
                            <td><textarea id='projCreat' rows='2' style='width:100%;' name='projCreat'></textarea></td>
                        </tr>
                        <tr>
                            <th>Subjects (';' seperated):</th>
                            <td><textarea id='projSubs' rows='2' style='width:100%;' name='projSubs'></textarea></td>
                        </tr>
                        <tr>
                            <th COLSPAN='2' style='text-align: center'>
                                <button id="updateMetadataButton" dojoType="dijit.form.Button" onclick="doProjEdits">Update Project Description</button>
                                <!-- a href='javascript:doProjEdits();'>Update Project Description</a -->
                            </th>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="footerCell">
                <?php echo $this->footer; ?>
            </td>
        </tr>
    </table>
    </body>   
</html>
