<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <link id="themeStyles" rel="stylesheet" href="/public/scripts/dojoroot/dijit/themes/tundra/tundra.css">
        <style type="text/css">
            @import "/public/scripts/dojoroot/dojo/resources/dojo.css";
            @import "/public/scripts/dojoroot/dojox/grid/resources/tundraGrid.css";
            @import "/public/scripts/dojoroot/dojox/layout/resources/FloatingPane.css";
            @import "/public/styles/importer.css";         
            @import "/public/styles/navigation.css";               
        </style>        
        <script type="text/javascript" src="/public/scripts/json2.js"></script>
        <script type="text/javascript" src="/public/scripts/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/dojoroot/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
        <script type="text/javascript" src="/public/scripts/prototype-1.6.0.2.js"></script>
        
        <!-- custom application-level script files -->
        <script type="text/javascript" src="/public/scripts/application/importer/wizard.js"></script>
        <script type="text/javascript" src="/public/scripts/application/browserDetect.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/navigation.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/xmlfeed.js"></script>
        
        <script type="text/javascript">        
            dojo.require("dojo.parser");
            dojo.require("dojo.data.ItemFileWriteStore");
            dojo.require("dojox.grid.DataGrid");
            dojo.require("dojox.grid.cells");
            dojo.require("dijit.Dialog");
            dojo.require("dijit.form.TextBox");
            dojo.require("dijit.form.Button");
            dojo.require("dojox.layout.FloatingPane");            
            dojo.require("dijit.TitlePane");
            dojo.require("dijit.Tree");
            dojo.require("dijit.ProgressBar");
  
            dojo.require("dojo.io.iframe");
            dojo.require("dojox.data.QueryReadStore");
	    
	    //dojo.require("dijit.layout.AccordionContainer");
	    //dojo.require("dijit.layout.SplitContainer");
	    
	    dojo.require("dojo.dnd.Container");
	    dojo.require("dojo.dnd.Manager");
	    dojo.require("dojo.dnd.Source");
            
            dojo.require("dijit.form.ComboBox");
            dojo.require("dijit.form.FilteringSelect");
            dojo.require("dojox.form.DropDownSelect");
            
            
            <?php echo $this->state; ?>
                       
            //include all of the functions that need to be called on startup:
            dojo.addOnLoad(function()
            {
                initXmlPane();
                
                //hide initialization HTML until importer has completely loaded:
                dojo.byId('loaderInner').innerHTML += " done.";
                setTimeout(function hideLoader(){
                        var loader = dojo.byId('loader'); 
                        dojo.fadeOut({ node: loader, duration:500,
                                onEnd: function(){ 
                                        loader.style.display = "none"; 
                                }
                        }).play();
                }, 250);
            });
        </script>
    
    </head>
    <body class="tundra">
        <div id="loader"><div id="loaderInner">Loading Importer ... </div></div>
        <br />  
        
        <div>
            Name: <strong><span id="spanUserName"></span></strong><br />
            Project Selected: <strong><span id="spanProjectSelected"></span></strong> 
        </div>
        <table id="mainTable" class="mainTable" align="center">
        <tr>
            <td colspan="2" class="headerCell">
                <?php echo $this->header; ?>
                <div id="errorMessage"></div>
            </td>
        </tr>
        <tr>
            <td class="navCell">
                <?php echo $this->sidebar; ?>
            </td>
            <td class="contentCell" id="contentCell">
                <?php echo $this->partial("wizardHeader.phtml") ?>
                <div style="overflow: auto; height: 400px;">
                    <br />
                    <div id="xmlStatusTable" style="text-align: center;"></div>
                    <div style="text-align: center;">                
                        <button dojoType="dijit.form.Button" id="processXMLButton" onclick="processObjects();">
                            Process XML Files...
                        </button>
                        <div dojoType="dijit.ProgressBar" style="width: 300px; margin-left: 190px"
                            jsId="dataTransformProgress"
                            id="dataTransformProgress"
                            class="tundra">				    
                        </div>
                    </div>
                    <div id="xmlTransformResultsProject" style="text-align: left;"></div>
                    <div id="xmlTransformResultsSpace" style="text-align: left;"></div>
                    <div id="xmlTransformResultsDiary" style="text-align: left;"></div>                    
                    <div id="xmlTransformResultsPeople" style="text-align: left;"></div>               
                    <div id="xmlTransformResultsResources" style="text-align: left;"></div>                
                    <div id="xmlTransformResultsProperties" style="text-align: left;"></div>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="footerCell">
                <?php echo $this->footer; ?>
            </td>
        </tr>
    </table>
    </body>   
</html>

<!-- !DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>XmlfeedController</title>
</head>
<body>
    <h1>XmlfeedController</h1>
    <a href='public/xmlFiles/<?php echo $this->fileName ?>'>XML Document</a>
</body>
</html-->
