<?php

$itemsObj = $this->itemsObj;
$requestParams = $this->requestParams;
if($itemsObj->itemData){
    $itemData = $itemsObj->itemData;
}
else{
    $itemData = false;
}


?>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Editorial Functions for Individual Items</title>
        <link href="../public/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/bootstrap-responsive.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-general.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-ex-tables.css"  rel="stylesheet" type="text/css" />
        
        
        <!-- <script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript" ></script> -->
        <script src="../public/scripts/application/editorial/widgets.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/jquery.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/bootstrap-tab.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/bootstrap-dropdown.js" type="text/javascript" ></script>
        <script type="text/javascript" src="/public/scripts/json2.js"></script>
        <script type="text/javascript" src="/public/scripts/utils.js"></script>
        <script type="text/javascript" src="../public/scripts/application/editorial/prototype.js"></script>
        
        <script src="../public/scripts/application/editorial/itemEdits.js" type="text/javascript" ></script>
        <!-- <script src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize" type="text/javascript" ></script> -->
        
        <style type="text/css">
            
        #map-canvas{
            width:300px;
            height:300px;
            margin:2%;
		  }
        </style>
        
        
        
    </head>
    <body id="docBody">
        <div id="main">
            <div id="main_content">
                <h2>Editorial Functions for Items:</h2>
                
                <div style="padding:5%;">
                    <?php 
                    
                    if($itemsObj->itemUUID){
                    ?>    
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Label</th>
                                    <th>UUID</th>
                                    <th>Type</th>
                                    <th>Project</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="info">
                                    <td><h4><?php echo $itemsObj->itemLabel; ?></h4></td>
                                    <td>
                                        <p>
                                            <small>
                                                <a href="<?php echo $itemsObj->itemPreview; ?>" target="_blank"><?php echo $itemsObj->itemUUID; ?></a>
                                                <br/>
                                                <a href="<?php echo $itemsObj->itemJSONdata; ?>" target="_blank">[JSON]</a>
                                                <a href="<?php echo $itemsObj->itemXMLdata; ?>" target="_blank">[XML]</a>
                                            </small>
                                        </p>
                                    </td>
                                    <td><?php echo $itemsObj->itemType; ?></td>
                                    <td><p class="muted">
                                        <?php echo $itemsObj->projectName; ?>
                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        
                    <?php    
                    } // end case with a variable
                    
                    ?>
                </div>
                
                
                <ul class="nav nav-tabs">
                    <li <?php echo $itemsObj->makeTabLiClass("basicData");?> ><a href="#basicData" data-toggle="tab">Basic Data</a></li>
                    <li <?php echo $itemsObj->makeTabLiClass("itemDes");?> ><a href="#itemDes" data-toggle="tab">Item Description</a></li>
                    <li <?php echo $itemsObj->makeTabLiClass("itemLinks");?> ><a href="#itemLinks" data-toggle="tab">Item Links</a></li>
                    <li <?php echo $itemsObj->makeTabLiClass("chrono");?> ><a href="#chrono" data-toggle="tab">Chronology</a></li>
                    <li <?php echo $itemsObj->makeTabLiClass("itemGeo");?> ><a href="#itemGeo" data-toggle="tab">Geospatial</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">New Items <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#subjectNew" data-toggle="tab">Make New Subject</a></li>
                            <li><a href="#mediaNew" data-toggle="tab">Make New Media</a></li>
                            <li><a href="#docNew" data-toggle="tab">Make New Document</a></li>
                            <li><a href="#personNew" data-toggle="tab">Make New Person</a></li>
                        </ul>
                    </li>
                </ul>
                   
                  <div class="tab-content">
                    
                    <div <?php echo $itemsObj->makeTabDivClass("basicData");?> id="basicData">
                        <h4>Basic Item Data</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Labeling</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/update-label">
                                        <input type="hidden" name="uuid" value="<?php echo $itemsObj->itemUUID; ?>" />
                                        <div class="control-group">
                                            <label class="control-label" for="itemLabel">Item Label</label>
                                            <div class="controls">
                                                <input name="label" type="text" class="input-large" id="itemLabel" value="<?php echo $itemsObj->itemLabel; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button id="labelSubmit" type="submit" class="btn">Update Label</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                </div>
                            </div>
                            <?php
                            if($itemsObj->itemTypeJSON == "space" && is_array($itemData)){
                               $itemClasses = $itemsObj->getRepresentedClasses(false);
                            ?>
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Item Class</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/update-class">
                                        <input type="hidden" name="uuid" value="<?php echo $itemsObj->itemUUID; ?>" />
                                        <div class="control-group">
                                            <label class="control-label" for="itemClassUUID">Item Class UUID</label>
                                            <div class="controls">
                                                <input name="classUUID" type="text" class="input-large" id="itemClassUUID" value="<?php echo $itemData["classID"]; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="itemClassName">Item Class Name</label>
                                            <div class="controls">
                                                <span id="itemClassName" class="input-large uneditable-input"><?php echo $itemData["className"]; ?></span>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Update Class</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                <?php
                                    if(is_array($itemClasses)){
                                        foreach($itemClasses as $itemClass){
                                        ?>    
                                        <label class="radio">
                                            <input id="<?php echo $itemClass["classUUID"]; ?>" type="radio" name="itemClass" value="<?php echo $itemClass["classUUID"]; ?>" onclick="javascript:updateClass('<?php echo $itemClass["classLabel"]; ?>');">
                                            <?php echo $itemClass["classLabel"]; ?>
                                        </label>
                                        <?php
                                        
                                        }//end loop through array
                                    }//end case with an array
                                ?>
                                </div>
                            </div>
                            <?php
                            
                            }//end case where we show a class form
                            else{
                            ?>    
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                </div>
                            <?php    
                            }//end case where we have no class form
                            ?>
                        </div>
                    </div>
                    
                    
                    
                    <div <?php echo $itemsObj->makeTabDivClass("itemDes");?> id="itemDes">
                        <h4>Item Description</h4>
                        <table class="table table-striped table-condensed table-hover table-bordered data-tab">
                            <thead>
                                <tr>
                                    <th style="width:15%;">PropertyUUID</th>
                                    <th style="width:15%;">VariableUUID</th>
                                    <th style="width:15%;">ValueUUID</th>
                                    <th>Variable Label</th>
                                    <th>Value Text</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                                
                        if(isset($itemData["propertiesObj"]["properties"])){
                            if(is_array($itemData["propertiesObj"]["properties"])){
                                foreach($itemData["propertiesObj"]["properties"] as $obsKey => $propsArray){
                                    foreach($propsArray as $propUUIDkey => $propArray){
                                    ?>    
                                    <tr>
                                        <td><p><small><?php echo $propUUIDkey; ?></small></p>
                                            <form method="POST" action="../editorial/delete-item-prop">
                                                <input type="hidden" name="propUUID" value="<?php echo $propUUIDkey; ?>" />
                                                <input type="hidden" name="itemUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <button class="btn btn-warning btn-mini" type="submit" title="Remove property from item">X</button>
                                            </form>
                                        </td>
                                        <td><p><small><a title="<?php echo $propArray["varType"]; ?>" href="../editorial/variables?varUUID=<?php echo $propArray["varUUID"]; ?>"><?php echo $propArray["varUUID"]; ?></small></p></td>
                                        <td><p><small><?php echo $propArray["valUUID"]; ?></small></p></td>
                                        <td><?php echo $propArray["varLabel"]; ?></td>
                                        <td><?php echo $propArray["showVal"]; ?></td>
                                    </tr>
                            <?php
                                    }//end loop through propereies
                                
                                }//end loop through observations
                            }//end case with array of properties
                        }//end case with properties
                            ?>
                            </tbody>
                        </table>
                    </div> 
                    
                    <div <?php echo $itemsObj->makeTabDivClass("itemLinks");?> id="itemLinks">
                        <h4>Item Links</h4>
                        <table class="table table-striped table-condensed table-hover table-bordered data-tab">
                            <thead>
                                <tr>
                                    <th style="width:10%;">Remove</th>
                                    <th style="width:15%;">TargetUUID</th>
                                    <th>Link Type</th>
                                    <th>Target Type</th>
                                    <th>Target Name</th>
                                    <th>Target Description</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                                
                        if(isset($itemData["linksObj"]["spaceLinks"])){
                            if(is_array($itemData["linksObj"]["spaceLinks"])){
                                foreach($itemData["linksObj"]["spaceLinks"] as $obsKey => $linksArray){
                                    foreach($linksArray as $key => $linkArray){
                                    ?>    
                                    <tr>
                                        <td>
                                            <form method="POST" action="../editorial/delete-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <button class="btn btn-warning btn-mini" type="submit" title="Remove this link">X</button>
                                            </form>
                                        </td>
                                        <td><p><small><a title="Edit <?php echo $linkArray["linkedName"]; ?>" href="../editorial/items?uuid=<?php echo $linkArray["linkedUUID"]; ?>"><?php echo $linkArray["linkedUUID"]; ?></small></p></td>
                                        <td>
                                            <form method="POST" action="../editorial/update-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <input type="text" name="newLinkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <button class="btn btn-mini" type="submit" title="Update linking relation">Update</button>
                                            </form>
                                        </td>
                                        <td>Subject (Location/Object)</td>
                                        <td><?php echo $linkArray["linkedName"]; ?><br/>(<?php echo $linkArray["className"]; ?>)</td>
                                        <td>
                                        <?php
                                            $contain = false;
                                            foreach($linkArray["containment"] as $tree => $parents){
                                                if(!$contain){
                                                    foreach($parents as $parent){
                                                        if(!$contain){
                                                            $contain = $parent["label"];
                                                        }
                                                        else{
                                                            $contain .= " / ".$parent["label"];
                                                        }
                                                    }
                                                }
                                            }
                                            echo $contain;
                                        ?>
                                        </td>
                                    </tr>
                            <?php
                                    }//end loop through links
                                
                                }//end loop through observations
                            }//end case with array of links
                        }//end case with links
                    
                        if(isset($itemData["linksObj"]["mediaLinks"])){
                            if(is_array($itemData["linksObj"]["mediaLinks"])){
                                foreach($itemData["linksObj"]["mediaLinks"] as $obsKey => $linksArray){
                                    foreach($linksArray as $key => $linkArray){
                                    ?>    
                                    <tr>
                                        <td>
                                            <form method="POST" action="../editorial/delete-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <button class="btn btn-warning btn-mini" type="submit" title="Remove this link">X</button>
                                            </form>
                                        </td>
                                        <td><p><small><a title="Edit <?php echo $linkArray["linkedName"]; ?>" href="../editorial/items?uuid=<?php echo $linkArray["linkedUUID"]; ?>"><?php echo $linkArray["linkedUUID"]; ?></small></p></td>
                                         <td>
                                            <form method="POST" action="../editorial/update-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <input type="text" name="newLinkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <button class="btn btn-mini" type="submit" title="Update linking relation">Update</button>
                                            </form>
                                        </td>
                                        <td>Media</td>
                                        <td><?php echo $linkArray["linkedName"]; ?><br/>(<?php echo $linkArray["archaeoMLtype"]; ?>)</td>
                                        <td><img src="<?php echo $linkArray["thumbURI"]; ?>" /></td>
                                    </tr>
                            <?php
                                    }//end loop through links
                                
                                }//end loop through observations
                            }//end case with array of links
                        }//end case with links
                    
                        if(isset($itemData["linksObj"]["documentLinks"])){
                            if(is_array($itemData["linksObj"]["documentLinks"])){
                                foreach($itemData["linksObj"]["documentLinks"] as $obsKey => $linksArray){
                                    foreach($linksArray as $key => $linkArray){
                                    ?>    
                                    <tr>
                                        <td>
                                            <form method="POST" action="../editorial/delete-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <button class="btn btn-warning btn-mini" type="submit" title="Remove this link">X</button>
                                            </form>
                                        </td>
                                        <td><p><small><a title="Edit <?php echo $linkArray["linkedName"]; ?>" href="../editorial/items?uuid=<?php echo $linkArray["linkedUUID"]; ?>"><?php echo $linkArray["linkedUUID"]; ?></small></p></td>
                                        <td>
                                            <form method="POST" action="../editorial/update-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <input type="text" name="newLinkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <button class="btn btn-mini" type="submit" title="Update linking relation">Update</button>
                                            </form>
                                        </td>
                                        <td>Document</td>
                                        <td><?php echo $linkArray["linkedName"]; ?></td>
                                        <td></td>
                                    </tr>
                            <?php
                                    }//end loop through links
                                
                                }//end loop through observations
                            }//end case with array of links
                        }//end case with links
                    
                    
                        if(isset($itemData["linksObj"]["personLinks"])){
                            if(is_array($itemData["linksObj"]["personLinks"])){
                                foreach($itemData["linksObj"]["personLinks"] as $obsKey => $linksArray){
                                    foreach($linksArray as $key => $linkArray){
                                    ?>    
                                    <tr>
                                        <td>
                                           <form method="POST" action="../editorial/delete-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <button class="btn btn-warning btn-mini" type="submit" title="Remove this link">X</button>
                                            </form>
                                        </td>
                                        <td><p><small><a title="Edit <?php echo $linkArray["linkedName"]; ?>" href="../editorial/items?uuid=<?php echo $linkArray["linkedUUID"]; ?>"><?php echo $linkArray["linkedUUID"]; ?></small></p></td>
                                        <td>
                                            <form method="POST" action="../editorial/update-item-link">
                                                <input type="hidden" name="originUUID" value="<?php echo $itemsObj->itemUUID; ?>" />
                                                <input type="hidden" name="targUUID" value="<?php echo $linkArray["linkedUUID"]; ?>" />
                                                <input type="hidden" name="linkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <input type="hidden" name="linkRelUUID" value="<?php
                                                if(isset($linkArray["linkRelUUID"])){
                                                    echo $linkArray["linkRelUUID"];
                                                }
                                                else{
                                                    echo false;
                                                }
                                                ?>" />
                                                <input type="text" name="newLinkType" value="<?php echo $linkArray["linkType"]; ?>" />
                                                <button class="btn btn-mini" type="submit" title="Update linking relation">Update</button>
                                            </form>
                                        </td>
                                        <td>Document</td>
                                        <td><?php echo $linkArray["linkedName"]; ?></td>
                                        <td><?php
                                        if(isset($linkArray["cite"])){
                                            echo $linkArray["cite"];
                                        }
                                        ?></td>
                                    </tr>
                            <?php
                                    }//end loop through links
                                
                                }//end loop through observations
                            }//end case with array of links
                        }//end case with links
                        
                    ?>
                            </tbody>
                        </table>
                        
                        <!-- Optional linking data -->
                        <div style="border-style:dashed; border-width:1px; padding:1%; margin-bottom: 1%;">
                            <h6>Add New Linking Relation</h6>
                            <form class="form-horizontal" method="post" action="../editorial/create-item-link">
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewActItemUUID">Active Item UUID</label>
                                    <div class="controls">
                                        <input name="actItemUUID" type="text" size="80" style="font-size:70%;" id="LinkNewItemUUID" value="<?php echo $itemsObj->itemUUID; ?>" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewActItemType">Active Item Type</label>
                                    <div class="controls">
                                        <input name="actItemType" type="text" size="80" style="font-size:70%;" id="LinkNewActItemType" value="<?php echo $itemsObj->itemType; ?>" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewProjUUID">Project UUID</label>
                                    <div class="controls">
                                        <input name="projUUID" type="text" size="80" style="font-size:70%;" id="LinkNewProjUUID" value="<?php echo $itemsObj->projectUUID; ?>" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">New Linked Item Origin or Target of Relationship</label>
                                    <div class="controls">
                                        <label class="radio">
                                            Target
                                            <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                        </label>
                                        <label class="radio">
                                            Origin
                                            <input type="radio" name="linkedItemPosition" value="origin" />
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">New Linked Item Type</label>
                                    <div class="controls">
                                        <label class="radio">
                                            Subject
                                            <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="subject" checked="true" />
                                        </label>
                                        <label class="radio">
                                            Media
                                            <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="media" />
                                        </label>
                                        <label class="radio">
                                            Document
                                            <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="document" />
                                        </label>
                                        <label class="radio">
                                            Project
                                            <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="project" />
                                        </label>
                                        <label class="radio">
                                            Person
                                            <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="person" />
                                        </label>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewLinkedItemType">New Link Item Type (from above)</label>
                                    <div class="controls">
                                        <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedItemType" value="subject" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewLinkedUUID">New Link Item UUID<br/><div id="newLinkLinkedItemData"></div></label>
                                    <div class="controls">
                                        <input onchange="javascript:getLinkingItemData('newLink');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedUUID" value="" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="LinkNewLinkedRelType">New Link Relation Type</label>
                                    <div class="controls">
                                        <input name="linkType" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedRelType" value="link" >
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="PersonNewSubmit">Create New Link</label>
                                    <div class="controls">
                                        <button id="LinkNewSubmit" class="btn btn-inverse" type="submit" title="Create the new link">Create Link!</button>
                                    </div>
                                </div>
                            </form>  
                        </div>
                        <!-- end optional linking data --> 
                            
                    </div> 
                    
                    
                    <div <?php echo $itemsObj->makeTabDivClass("chrono");?> id="chrono">
                        <h4>Chronology</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Chronology Form</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/chrono-tag-item">
                                        <input type="hidden" name="uuid" value="<?php echo $itemsObj->itemUUID; ?>" />
                                        <input type="hidden" name="projUUID" value="<?php echo $itemsObj->projectUUID; ?>" />
                                        <div class="control-group">
                                            <label class="control-label" for="tStart">Start Time</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <input name="tStart" type="text" class="input-large" id="tStart" value="<?php echo $itemData["chronoArray"][0]["start_time"]; ?>" >
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <input name="tStart" type="text" class="input-large" id="tStart" placeholder="(Start time)" >
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="tEnd">End Time</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <input name="tEnd" type="text" class="input-large" id="tEnd" value="<?php echo $itemData["chronoArray"][0]["end_time"]; ?>" >
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <input name="tEnd" type="text" class="input-large" id="tEnd" placeholder="(End time)" >
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="timeRange">Time Range</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <span id="timeRange" class="input-large uneditable-input"><?php echo $itemData["chronoArray"][0]["label"]; ?></span>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <span id="timeRange" class="input-large uneditable-input">[Time range]</span>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="timeSourceUUID">Chronology Tag Source UUID</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                               
                                            ?>
                                            
                                            <span id="timeSourceUUID" class="input-large uneditable-input"><?php echo $itemData["chronoArray"][0]["chronoSource"]; ?></span>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <span id="timeSourceUUID" class="input-large uneditable-input">[Time Source UUID]</span>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="timeSourceLabel">Chronology Tag Source Label</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                               
                                            ?>
                                            
                                            <span id="timeSourceLabel" class="input-large uneditable-input"><?php echo $itemData["chronoArray"][0]["sourceName"]; ?></span>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <span id="timeSourceLabel" class="input-large uneditable-input">[Time Source Label]</span>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Submit</button>
                                            </div>
                                        </div>
                                    </form>
                                
                                
                                </div>
                                
                                <div class="divCell" >
                                    <h6>Instructions</h6>
                                    <p>Ideally, most fields (variables) should have documentation.</p>
                                </div>
                            
                            </div>
                            
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Two Variables Chronology Form</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/chrono-tag-by-vars">
                                        <input type="hidden" name="uuid" value="<?php echo $itemsObj->itemUUID; ?>" />
                                        <input type="hidden" name="projUUID" value="<?php echo $itemsObj->projectUUID; ?>" />
                                        <div class="control-group">
                                            <label class="control-label" for="aVar">Start Time</label>
                                            <div class="controls">
                                                <input name="AvarUUID" type="text" class="input-large" id="aVar" placeholder="(VarID with start time)" >
                                            </div>
                                        </div>
                                         <div class="control-group">
                                            <label class="control-label" for="bVar">Start Time</label>
                                            <div class="controls">
                                                <input name="BvarUUID" type="text" class="input-large" id="bVar" placeholder="(VarID with end time)" >
                                            </div>
                                        </div>
                                        
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Submit</button>
                                            </div>
                                        </div>
                                    </form>
                                
                                
                                </div>
                                
                                <div class="divCell" >
                                    <h6>Instructions</h6>
                                    <p>Ideally, most fields (variables) should have documentation.</p>
                                </div>
                            
                            </div>
                            
                        </div>
                    </div>
            
                    <div <?php echo $itemsObj->makeTabDivClass("itemGeo");?> id="itemGeo">
                        <h4>Geo-Spatial</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:55%; background-color:#f7f7f7;">
                                    <h6>GeoSpatial Form</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/geo-tag-item">
                                        <input type="hidden" name="uuid" value="<?php echo $itemsObj->itemUUID; ?>" />
                                        <input type="hidden" name="projUUID" value="<?php echo $itemsObj->projectUUID; ?>" />
                                        <div class="control-group">
                                            <label class="control-label" for="itemLat">Latitude (WSG84 Decimal Degrees)</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <input name="lat" type="text" class="input-large" id="itemLat" value="<?php echo $itemData["geoLat"]; ?>" >
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <input name="lat" type="text" class="input-large" id="itemLat"  value="0.0" />
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="itemLon">Longitude (WSG84 Decimal Degrees)</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <input name="lon" type="text" class="input-large" id="itemLon" value="<?php echo $itemData["geoLon"]; ?>" >
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <input name="lon" type="text" class="input-large" id="itemLon" value="0.0" />
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="itemGeoJSON">GeoJSON</label>
                                            <div class="controls">
                                            <?php
                                            $geoJSON = false;
                                            if(is_array($itemData)){
                                                if(is_array($itemData["geoJSON"])){
                                                    $geoJSON = true;
                                                }
                                            }
                                            
                                            if($geoJSON){
                                            ?>
                                            
                                            <textarea name="geoJSON" id="itemGeoJSON" class="field span4" rows="6">
                                            <?php
                                                echo Zend_Json::encode($itemData["geoJSON"]);
                                            ?>
                                            </textarea>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <textarea name="geoJSON" id="itemGeoJSON" class="field span4" rows="6"></textarea>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="itemGeoKML">KML</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                                
                                            ?>
                                            
                                            <textarea name="geoKML" id="itemGeoKML" class="field span4" rows="6"><?php echo $itemData["geoKML"]; ?></textarea>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <textarea name="geoKML" id="itemGeoKML" class="field span4" rows="6"></textarea>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="geoSourceLabel">Geo-data Source Label</label>
                                            <div class="controls">
                                            <?php
                                            if(is_array($itemData)){
                                               
                                            ?>
                                            
                                            <span id="geoSourceLabel" class="input-large uneditable-input"><?php echo $itemData["geoSourceName"]; ?></span>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <span id="geoSourceLabel" class="input-large uneditable-input">[Geo Source Label]</span>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Submit</button>
                                            </div>
                                        </div>
                                    </form>
                                
                                
                                </div>
                                
                                <div class="divCell" >
                                    <h6>Map</h6>
                                    <p>Drag map marker to new location if needed.</p>
                                    <div id="map-canvas"></div>
                                </div>
                            
                            </div>
                        </div>
                    </div>
                  
                  
                  
                  
                    <div <?php echo $itemsObj->makeTabDivClass("subjectNew");?> id="subjectNew">
                        <h4>Manually Create a New Subject (Location/Object) Item</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Subjects (Locations / Objects)</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/create-subject-item">
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewUUID">New UUID</label>
                                            <div class="controls">
                                                <input name="newUUID" type="text" size="80" style="font-size:70%;" id="SubjectNewUUID" value="<?php echo GenericFunctions::generateUUID(); ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewProjUUID">Project UUID</label>
                                            <div class="controls">
                                                <input name="projUUID" type="text" size="80" style="font-size:70%;" id="SubjectNewProjUUID" value="<?php echo $itemsObj->projectUUID; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewSourceID">Source ID</label>
                                            <div class="controls">
                                                <input name="sourceID" type="text" size="80" style="font-size:70%;" id="SubjectNewSourceID" value="manual" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewLabel">Item Label</label>
                                            <div class="controls">
                                                <input name="label" type="text" size="80" style="font-size:70%;" id="SubjectNewLabel" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewClassUUID">Class UUID</label>
                                            <div class="controls">
                                                <input name="classUUID" type="text" size="80" style="font-size:70%;" id="SubjectNewClassUUID" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewClassName">New Item Class Name</label>
                                            <div class="controls">
                                                <span id="SubjectNewClassName" class="input-large uneditable-input"><?php echo $itemData["className"]; ?></span>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewParUUID">Parent UUID (Optional)<br/><div id="SubjectParData"></div></label>
                                            <div class="controls">
                                                <input onchange="javascript:getParentData();" name="parentUUID" type="text" size="80" style="font-size:70%;" id="SubjectNewParUUID" value="None" >
                                            </div>
                                        </div>
                                        
                                        <!-- Optional linking data -->
                                        <div style="border-style:dashed; border-width:1px; padding:1%; margin-bottom: 1%;">
                                            <h6>Optional Linking Relation</h6>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Origin or Target of Relationship</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Target
                                                        <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Origin
                                                        <input type="radio" name="linkedItemPosition" value="origin" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Type</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Subject
                                                        <input onchange="javascript:updateLinkedItemType('newSubject');" type="radio" name="newSubjectLinkedType" value="subject" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Media
                                                        <input onchange="javascript:updateLinkedItemType('newSubject');" type="radio" name="newSubjectLinkedType" value="media" />
                                                    </label>
                                                    <label class="radio">
                                                        Document
                                                        <input onchange="javascript:updateLinkedItemType('newSubject');" type="radio" name="newSubjectLinkedType" value="document" />
                                                    </label>
                                                    <label class="radio">
                                                        Project
                                                        <input onchange="javascript:updateLinkedItemType('newSubject');" type="radio" name="newSubjectLinkedType" value="project" />
                                                    </label>
                                                    <label class="radio">
                                                        Person
                                                        <input onchange="javascript:updateLinkedItemType('newSubject');" type="radio" name="newSubjectLinkedType" value="person" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="SubjectNewLinkedItemType">Link Item Type (from above)</label>
                                                <div class="controls">
                                                    <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="SubjectNewLinkedItemType" value="subject">
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="SubjectNewLinkedUUID">Link Item UUID<br/><div id="newSubjectLinkedItemData"></div></label>
                                                <div class="controls">
                                                    <input onchange="javascript:getLinkingItemData('newSubject');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="SubjectNewLinkedUUID" value="" >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="SubjectNewLinkedRelType">Link Relation Type</label>
                                                <div class="controls">
                                                    <input name="linkType" type="text" size="80" style="font-size:70%;" id="SubjectNewLinkedRelType" value="link" >
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end optional linking data -->
                                        
                                        
                                        <div class="control-group">
                                            <label class="control-label" for="SubjectNewSubmit">Create New Subject (Location/Object)</label>
                                            <div class="controls">
                                                <button id="SubjectNewSubmit" class="btn btn-inverse" type="submit" title="Create the new resource">Create Subject!</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell">
                                    <h6>Select a Class:</h6>
                                    <form class="form-horizontal">
                                    <?php
                                    $itemClasses = $itemsObj->getRepresentedClasses(false);
                                    if(is_array($itemClasses)){
                                        foreach($itemClasses as $itemClass){
                                        ?>    
                                        <label class="radio">
                                            <input id="<?php echo $itemClass["classUUID"]; ?>" type="radio" name="newItemClass" value="<?php echo $itemClass["classUUID"]; ?>" onclick="javascript:updateNewClass('<?php echo $itemClass["classLabel"]; ?>');">
                                            <?php echo $itemClass["classLabel"]; ?>
                                        </label>
                                        <?php
                                        
                                        }//end loop through array
                                    }//end case with an array
                                    ?>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div <?php echo $itemsObj->makeTabDivClass("mediaNew");?> id="mediaNew">
                        <h4>Manually Create a New Media Item</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Media Resources</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/create-media-item">
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewUUID">New UUID</label>
                                            <div class="controls">
                                                <input name="newUUID" type="text" size="80" style="font-size:70%;" id="MediaNewUUID" value="<?php echo GenericFunctions::generateUUID(); ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewProjUUID">Project UUID</label>
                                            <div class="controls">
                                                <input name="projUUID" type="text" size="80" style="font-size:70%;" id="MediaNewProjUUID" value="<?php echo $itemsObj->projectUUID; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewSourceID">Source ID</label>
                                            <div class="controls">
                                                <input name="sourceID" type="text" size="80" style="font-size:70%;" id="MediaNewSourceID" value="manual" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewLabel">Item Label</label>
                                            <div class="controls">
                                                <input name="label" type="text" size="80" style="font-size:70%;" id="MediaNewLabel" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewFileName">File Name</label>
                                            <div class="controls">
                                                <input name="filename" type="text" size="80" style="font-size:70%;" id="MediaNewFileName" value="" onchange="javascript:autoSuggestPaths();">
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewPathPrefix">File Path Prefix</label>
                                            <div class="controls">
                                                <input name="pathprefix" type="text" size="80" style="font-size:70%;" id="MediaNewPathPrefix" value="" onchange="javascript:autoSuggestPaths();" >
                                            </div>
                                        </div>
                                         <div class="control-group">
                                            <label class="control-label" for="MediaNewFull">Full File URI</label>
                                            <div class="controls">
                                                <input name="fullfile" type="text" size="80" style="font-size:70%;" id="MediaNewFull" value="" >
                                            </div>
                                            <div id="fullfile-newStatus" style="padding:2%; text-align: center;"></div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewPreview">Preview File URI</label>
                                            <div class="controls">
                                                <input name="preview" type="text" size="80" style="font-size:70%;" id="MediaNewPreview" value="" >
                                            </div>
                                            <div id="preview-newStatus" style="padding:2%; text-align: center;"></div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewThumb">Thumbnail URI</label>
                                            <div class="controls">
                                                <input name="thumb" type="text" size="80" style="font-size:70%;" id="MediaNewThumb" value="" >
                                            </div>
                                            <div id="thumb-newStatus" style="padding:2%; text-align: center;"></div>
                                        </div>
                                         <div class="control-group">
                                            <label class="control-label" for="fileCheck">Check Files</label>
                                            <div class="controls">
                                                <a class="btn" onclick="javascript:checkNewFiles();">Check</a>
                                            </div>
                                        </div>
                                         
                                        <!-- Optional linking data -->
                                        <div style="border-style:dashed; border-width:1px; padding:1%; margin-bottom: 1%;">
                                            <h6>Optional Linking Relation</h6>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Origin or Target of Relationship</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Target
                                                        <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Origin
                                                        <input type="radio" name="linkedItemPosition" value="origin" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Type</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Subject
                                                        <input onchange="javascript:updateLinkedItemType('newMedia');"type="radio" name="newMediaLinkedType" value="subject" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Media
                                                        <input onchange="javascript:updateLinkedItemType('newMedia');" type="radio" name="newMediaLinkedType" value="media" />
                                                    </label>
                                                    <label class="radio">
                                                        Document
                                                        <input onchange="javascript:updateLinkedItemType('newMedia');" type="radio" name="newMediaLinkedType" value="document" />
                                                    </label>
                                                    <label class="radio">
                                                        Project
                                                        <input onchange="javascript:updateLinkedItemType('newMedia');" type="radio" name="newMediaLinkedType" value="project" />
                                                    </label>
                                                    <label class="radio">
                                                        Person
                                                        <input onchange="javascript:updateLinkedItemType('newMedia');" type="radio" name="newMediaLinkedType" value="person" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="MediaNewLinkedItemType">Link Item Type (from above)</label>
                                                <div class="controls">
                                                    <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="MediaNewLinkedItemType" value="subject" />
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="MediaNewLinkedUUID">Link Item UUID<br/><div id="newMediaLinkedItemData"></div></label>
                                                <div class="controls">
                                                    <input onchange="javascript:getLinkingItemData('newMedia');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="MediaNewLinkedUUID" value="" >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="MediaNewLinkedRelType">Link Relation Type</label>
                                                <div class="controls">
                                                    <input name="linkType" type="text" size="80" style="font-size:70%;" id="MediaNewLinkedRelType" value="link" >
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end optional linking data --> 
                                         
                                         
                                         
                                        <div class="control-group">
                                            <label class="control-label" for="MediaNewSubmit">Create New Media</label>
                                            <div class="controls">
                                                <button id="MediaNewSubmit" class="btn btn-inverse" type="submit" title="Create the new resource">Create Media!</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div <?php echo $itemsObj->makeTabDivClass("docNew");?> id="docNew">
                        <h4>Manually Create a New Document Item</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Document (Diary / Narrative)</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/create-document-item">
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewUUID">New UUID</label>
                                            <div class="controls">
                                                <input name="newUUID" type="text" size="80" style="font-size:70%;" id="DocNewUUID" value="<?php echo GenericFunctions::generateUUID(); ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewProjUUID">Project UUID</label>
                                            <div class="controls">
                                                <input name="projUUID" type="text" size="80" style="font-size:70%;" id="DocNewProjUUID" value="<?php echo $itemsObj->projectUUID; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewSourceID">Source ID</label>
                                            <div class="controls">
                                                <input name="sourceID" type="text" size="80" style="font-size:70%;" id="DocNewSourceID" value="manual" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewLabel">Item Label</label>
                                            <div class="controls">
                                                <input name="label" type="text" size="80" style="font-size:70%;" id="DocNewLabel" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewContent">Document Context (XHTML)<br/><div id="docXHTMLval"></div></label>
                                            <div class="controls">
                                                <textarea name="content" onchange="javascript:checkXHTML();" class="field span5" id="DocNewContent" rows="8" placeholder="Enter XHTML content here"></textarea>
                                            </div>
                                        </div>
                                        
                                        <!-- Optional linking data -->
                                        <div style="border-style:dashed; border-width:1px; padding:1%; margin-bottom: 1%;">
                                            <h6>Optional Linking Relation</h6>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Origin or Target of Relationship</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Target
                                                        <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Origin
                                                        <input type="radio" name="linkedItemPosition" value="origin" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Type</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Subject
                                                        <input onchange="javascript:updateLinkedItemType('newDoc');"  type="radio" name="newDocLinkedType" value="subject" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Media
                                                        <input onchange="javascript:updateLinkedItemType('newDoc');" type="radio" name="newDocLinkedType" value="media" />
                                                    </label>
                                                    <label class="radio">
                                                        Document
                                                        <input onchange="javascript:updateLinkedItemType('newDoc');" type="radio" name="newDocLinkedType" value="document" />
                                                    </label>
                                                    <label class="radio">
                                                        Project
                                                        <input onchange="javascript:updateLinkedItemType('newDoc');" type="radio" name="newDocLinkedType" value="project" />
                                                    </label>
                                                    <label class="radio">
                                                        Person
                                                        <input onchange="javascript:updateLinkedItemType('newDoc');" type="radio" name="newDocLinkedType" value="person" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="DocNewLinkedItemType">Link Item Type (from above)</label>
                                                <div class="controls">
                                                    <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="DocNewLinkedItemType" value="subject" />
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="DocNewLinkedUUID">Link Item UUID<br/><div id="newDocLinkedItemData"></div></label>
                                                <div class="controls">
                                                    <input onchange="javascript:getLinkingItemData('newDoc');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="DocNewLinkedUUID" value="" >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="DocNewLinkedRelType">Link Relation Type</label>
                                                <div class="controls">
                                                    <input name="linkType" type="text" size="80" style="font-size:70%;" id="DocNewLinkedRelType" value="link" >
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end optional linking data --> 
                                        
                                        
                                        
                                        
                                        
                                        <div class="control-group">
                                            <label class="control-label" for="DocNewSubmit">Create New Document</label>
                                            <div class="controls">
                                                <button id="DocNewSubmit" class="btn btn-inverse" type="submit" title="Create the new document">Create Doc!</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell">
                                    
                                </div>
                            </div>
                        </div>
                    </div> <!-- end new document -->
                    <div <?php echo $itemsObj->makeTabDivClass("personNew");?> id="personNew">
                        <h4>Manually Create a New Person Item</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Person or Organization</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/create-person-item">
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewUUID">New UUID</label>
                                            <div class="controls">
                                                <input name="newUUID" type="text" size="80" style="font-size:70%;" id="PersonNewUUID" value="<?php echo GenericFunctions::generateUUID(); ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewProjUUID">Project UUID</label>
                                            <div class="controls">
                                                <input name="projUUID" type="text" size="80" style="font-size:70%;" id="PersonNewProjUUID" value="<?php echo $itemsObj->projectUUID; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewSourceID">Source ID</label>
                                            <div class="controls">
                                                <input name="sourceID" type="text" size="80" style="font-size:70%;" id="PersonNewSourceID" value="manual" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewLabel">Person Full Name</label>
                                            <div class="controls">
                                                <input name="label" type="text" size="80" style="font-size:70%;" id="PersonNewLabel" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewSurname">Surname</label>
                                            <div class="controls">
                                                <input name="surname" type="text" size="80" style="font-size:70%;" id="PersonNewSurname" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewGivenName">Given Name</label>
                                            <div class="controls">
                                                <input name="givenname" type="text" size="80" style="font-size:70%;" id="PersonNewGivenName" value="" >
                                            </div>
                                        </div>
                                         <div class="control-group">
                                            <label class="control-label" for="PersonNewMidInit">Middle Initial</label>
                                            <div class="controls">
                                                <input name="midinitial" type="text" size="8" style="font-size:70%;" id="PersonNewMidInit" value="" >
                                            </div>
                                        </div>
                                          <div class="control-group">
                                            <label class="control-label" for="PersonNewInitials">Initials</label>
                                            <div class="controls">
                                                <input name="initials" type="text" size="8" style="font-size:70%;" id="PersonNewInitials" value="" >
                                            </div>
                                        </div>
                                          
                                        <!-- Optional linking data -->
                                        <div style="border-style:dashed; border-width:1px; padding:1%; margin-bottom: 1%;">
                                            <h6>Optional Linking Relation</h6>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Origin or Target of Relationship</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Target
                                                        <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Origin
                                                        <input type="radio" name="linkedItemPosition" value="origin" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label">Linked Item Type</label>
                                                <div class="controls">
                                                    <label class="radio">
                                                        Subject
                                                        <input onchange="javascript:updateLinkedItemType('newPerson');" type="radio" name="newPersonLinkedType" value="subject" checked="true" />
                                                    </label>
                                                    <label class="radio">
                                                        Media
                                                        <input onchange="javascript:updateLinkedItemType('newPerson');" type="radio" name="newPersonLinkedType" value="media" />
                                                    </label>
                                                    <label class="radio">
                                                        Document
                                                        <input onchange="javascript:updateLinkedItemType('newPerson');" type="radio" name="newPersonLinkedType" value="document" />
                                                    </label>
                                                    <label class="radio">
                                                        Project
                                                        <input onchange="javascript:updateLinkedItemType('newPerson');" type="radio" name="newPersonLinkedType" value="project" />
                                                    </label>
                                                    <label class="radio">
                                                        Person
                                                        <input onchange="javascript:updateLinkedItemType('newPerson');" type="radio" name="newPersonLinkedType" value="person" />
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="PersonNewLinkedItemType">Link Item Type (from above)</label>
                                                <div class="controls">
                                                    <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="PersonNewLinkedItemType" value="subject" />
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="PersonNewLinkedUUID">Link Item UUID<br/><div id="newPersonLinkedItemData"></div></label>
                                                <div class="controls">
                                                    <input onchange="javascript:getLinkingItemData('newPerson');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="PersonNewLinkedUUID" value="" >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="PersonNewLinkedRelType">Link Relation Type</label>
                                                <div class="controls">
                                                    <input name="linkType" type="text" size="80" style="font-size:70%;" id="PersonNewLinkedRelType" value="link" >
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end optional linking data --> 
                                          
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewSubmit">Create New Person</label>
                                            <div class="controls">
                                                <button id="PersonNewSubmit" class="btn btn-inverse" type="submit" title="Create the new person">Create Person!</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
                  <!--end tab content -->
                  
                  <script>
                    
                    function getParameterByName(name) {
                        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
                        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                            results = regex.exec(location.search);
                        return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
                    }
                    
                    var selTab = getParameterByName("tab");
                    
                    if(selTab){
                        $(function () {
                            e.preventDefault();
                            $('#myTab a[href="#' + selTab + '"]').tab('show'); // Select tab by name
                        });
                    }
                    else{
                        $(function () {
                            $('#myTab a:first').tab('show');
                        });
                    }
                    
                   <?php
                    if(isset($requestParams["tab"])){
                    ?>    
                        
                    
                    <?php   
                    }//end case with a tab to select
                    ?>
                    
                  </script>    
            </div>
        </div>
    </body>
    <script type="text/javascript">
        window.onload = init;
        function init() {
            
            loadScript();
            if (window.Event) {
                document.captureEvents(Event.MOUSEMOVE);
            }
            document.onmousemove = getCursorXY;
            
        }
        
        var cursorX;
        var cursorY;
        function getCursorXY(e) {
            cursorX = (window.Event) ? e.pageX : event.clientX + (document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft);
            cursorY = (window.Event) ? e.pageY : event.clientY + (document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop);
        }
        
        function loadScript() {
            var script = document.createElement('script');
            script.type = 'text/javascript';
            script.src = 'https://maps.googleapis.com/maps/api/js?sensor=false&' +
           'callback=initialize';
            document.body.appendChild(script);
        }
        
    </script>
    <script type="text/javascript">
        function initialize() {
            var firstLat = document.getElementById("itemLat").value;
            var firstLon = document.getElementById("itemLon").value;
            
            var myLatlng = new google.maps.LatLng(firstLat,firstLon);
            
            var myOptions = {
                zoom: 4,
                center: myLatlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);
            
            var marker = new google.maps.Marker({
                position: myLatlng, 
                map: map,
                draggable: true,
                title:"Item location"
            });
   
   
            var userLat;
            var userLon;
   
            google.maps.event.addListener(marker, 'dragend', function( event){
                //alert( "New Longitude: "+event.latLng.lng()+" "+", latitude: "+event.latLng.lat() );
                userLat = event.latLng.lat();
                userLon = event.latLng.lng();
                document.getElementById("itemLon").value = userLon ;
                document.getElementById("itemLat").value = userLat ;
            });
        }
    </script>
</html>