<?php

$varObj = $this->varObj;
$requestParams = $this->requestParams;



?>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Editorial Functions for Variables</title>
        <link href="../public/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/bootstrap-responsive.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-general.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-ex-tables.css"  rel="stylesheet" type="text/css" />
        
        
        <script src="../public/scripts/application/editorial/widgets.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/jquery.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/bootstrap-tab.js" type="text/javascript" ></script>
        
        <script type="text/javascript" src="/public/scripts/json2.js"></script>
        <script type="text/javascript" src="/public/scripts/utils.js"></script>
        <script type="text/javascript" src="../public/scripts/application/editorial/prototype.js"></script>
        
        <script src="../public/scripts/application/editorial/variableEdits.js" type="text/javascript" ></script>
        <script src="../public/scripts/application/editorial/itemEdits.js" type="text/javascript" ></script>
        
        
        <script type="text/javascript">
           
            
            
        </script>
        
    </head>
    <body>
        <div id="main">
            <div id="main_content">
                <h2>Editorial Functions for Variables:</h2>
                
                <div style="padding:5%;">
                    <?php 
                    
                    if($varObj->varUUID){
                    ?>    
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Label</th>
                                    <th>UUID</th>
                                    <th>Type</th>
                                    <th>Project</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="info">
                                    <td><h4><?php echo $varObj->varLabel; ?></h4></td>
                                    <td><p><small><?php echo $varObj->varUUID; ?></small></p></td>
                                    <td><?php echo $varObj->varType; ?></td>
                                    <td><p class="muted">
                                        <?php echo $varObj->projectName; ?>
                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        
                    <?php    
                    } // end case with a variable
                    
                    ?>
                </div>
                
                
                <ul class="nav nav-tabs">
                    <li <?php echo $varObj->makeTabLiClass("varsList");?> ><a href="#varsList" data-toggle="tab">Variables</a></li>
                    <li <?php echo $varObj->makeTabLiClass("notes");?> ><a href="#notes" data-toggle="tab">Variable Notes</a></li>
                    <li <?php echo $varObj->makeTabLiClass("values");?> ><a href="#values" data-toggle="tab">Variable Values</a></li>
                    <li <?php echo $varObj->makeTabLiClass("unit-types");?> ><a href="#unit-types" data-toggle="tab">Variable Unit Types</a></li>
                    <li <?php echo $varObj->makeTabLiClass("linked-data");?> ><a href="#linked-data" data-toggle="tab">Variable Linked-Data</a></li>
                </ul>
                   
                  <div class="tab-content">
                    
                    <div <?php echo $varObj->makeTabDivClass("varsList");?> id="varsList">
                        <h4>Find a variable</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow" style="background-color:#f7f7f7;">
                                <div class="divCell" style="width:40%;">
                                    <h6>Search for a variable</h6>
                                    <form class="form-search">
                                        <div class="input-append">
                                            <input class="span2" id="varLook" type="text" >
                                            <button class="btn" type="button" onclick="varLookUp();">Find</button>
                                        </div>
                                    </form>
                                    <div id="vars" style="padding-top:10%;padding-left:5%;padding-right:5%;">
                                    
                                    </div>
                                </div>
                                <div class="divCell">
                                    <h6>Limit by Project:</h6>
                                    <form class="form-horizontal">
                                    <?php
                                    
                                    $varProjs = $varObj->getRepresentedProjects();
                                    if(is_array($varProjs)){
                                        $projChecked = false;
                                        foreach($varProjs as $proj){
                                        
                                        if($proj["projectUUID"] != $varObj->projectUUID){
                                        ?>    
                                        <label class="radio">
                                            <input type="radio" name="varProj" value="<?php echo $proj["projectUUID"]; ?>">
                                            <?php echo $proj["projectName"]; ?>
                                        </label>
                                        <?php
                                        }//end case where the project ID is not the same as the active variable's projectUUID
                                        else{
                                        ?>
                                        
                                        <label class="radio">
                                            <input type="radio" name="varProj" value="<?php echo $proj["projectUUID"]; ?>" checked>
                                            <?php echo $proj["projectName"]; ?>
                                        </label>
                                        
                                        <?php
                                        $projChecked = true;
                                        }//end case where the project ID is same as the active variable's projectUUID
                                        
                                        
                                        }//end loop through array
                                    }//end case with an array
                                    ?>
                                    
                                    <?php
                                    
                                    if(!$projChecked){
                                    
                                    ?>   
                                        <label class="radio">
                                            <input type="radio" name="varProj" value="0" checked>
                                            (Don't Limit)
                                        </label>
                                    <?php
                                    }//end case where the project ID has not been checked, so default to don't limit
                                    else{
                                    ?>
                                        <label class="radio">
                                            <input type="radio" name="varProj" value="0" >
                                            (Don't Limit)
                                        </label>
                                    
                                    <?php
                                    }//end case where the project ID has been checked, so don't default to no limit
                                    ?>
                                    </form>
                                </div>
                                <div class="divCell">
                                    <h6>Limit by Type:</h6>
                                    <form class="form-horizontal">
                                    <?php
                                    
                                    $varTypes = $varObj->getRepresentedVarTypes();
                                    if(is_array($varTypes)){
                                        foreach($varTypes as $varType){
                                        ?>    
                                        <label class="radio">
                                            <input type="radio" name="varType" value="<?php echo $varType; ?>">
                                            <?php echo $varType; ?>
                                        </label>
                                        <?php
                                        
                                        }//end loop through array
                                    }//end case with an array
                                    ?>
                                        <label class="radio">
                                            <input type="radio" name="varType" value="0" checked>
                                            (Don't Limit)
                                        </label>
                                    </form>
                                </div>
                                <div class="divCell">
                                    <h6>Limit by Use in a Class:</h6>
                                    <form class="form-horizontal">
                                    <?php
                                    
                                    $varClasses = $varObj->getRepresentedClasses();
                                    if(is_array($varClasses)){
                                        foreach($varClasses as $varClass){
                                        ?>    
                                        <label class="radio">
                                            <input type="radio" name="varClass" value="<?php echo $varClass["classUUID"]; ?>">
                                            <?php echo $varClass["classLabel"]; ?>
                                        </label>
                                        <?php
                                        
                                        }//end loop through array
                                    }//end case with an array
                                    ?>
                                        <label class="radio">
                                            <input type="radio" name="varClass" value="0" checked>
                                            (Don't Limit)
                                        </label>
                                    </form>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                    <div <?php echo $varObj->makeTabDivClass("notes");?> id="notes">
                        <h4>Add Documentation to a Variable</h4>
                        
                        <div class="divTab" style="width:100%;">
                            <div class="divRow">
                                <div class="divCell" style="width:66%; background-color:#f7f7f7;">
                                    <h6>Variable Documentation Form</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/var-add-note">
                                        <div class="control-group">
                                            <label class="control-label" for="noteVarUUID">Variable UUID</label>
                                            <div class="controls">
                                            <?php
                                            if($varObj->varUUID){
                                            ?>
                                            
                                            <input name="varUUID" type="text" class="input-large" id="noteVarUUID" value="<?php echo $varObj->varUUID; ?>" >
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <input name="varUUID" type="text" class="input-large" id="noteVarUUID" placeholder="(Select from list)" >
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="noteVarLabel">Variable Name</label>
                                            <div class="controls">
                                            
                                            <?php
                                            if($varObj->varUUID){
                                            ?>
                                            
                                            <span id="noteVarLabel" class="input-large uneditable-input"><?php echo $varObj->varLabel; ?></span>
                                            
                                            <?php
                                            }//end case with a variableUUID
                                            else{
                                            ?>
                                            
                                            <span id="noteVarLabel" class="input-large uneditable-input">(Select from list)</span>
                                          
                                            <?php
                                            }//end case without a variableUUID
                                            ?>
                                            
                                            
                                            
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="noteVarText">Note</label>
                                            <div class="controls">
                                                
                                                <?php
                                                if($varObj->varNote){
                                                ?>
                                                
                                                <textarea name="varNote" id="noteVarText" style="width:100%;" rows="5"><?php echo $varObj->varNote; ?></textarea>
                                                
                                                <?php
                                                }//end case with a varNote
                                                else{
                                                ?>
                                                
                                                <textarea name="varNote" id="noteVarText" style="width:100%;" rows="5"></textarea>
                                              
                                                <?php
                                                }//end case without a varNote
                                                ?>
                                                
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                
                                                <?php
                                                if($varObj->varNote && $varObj->varNoteXHTMLvalid){
                                                ?>
                                                    <button class="btn btn-small btn-success" type="button">XHTML valid</button>
                                                <?php
                                                }//end case with good XHTML
                                                elseif($varObj->varNote && !$varObj->varNoteXHTMLvalid){
                                                ?>
                                                    <button class="btn btn-small btn-danger" type="button">XHTML Invalid</button>
                                                <?php
                                                }//end case bad XHTML
                                                ?>
                                                <button type="submit" class="btn">Submit</button>
                                            </div>
                                        </div>
                                    </form>
                                
                                
                                </div>
                                
                                <div class="divCell" >
                                    <h6>Instructions</h6>
                                    <p>Ideally, most fields (variables) should have documentation.</p>
                                </div>
                            
                            </div>
                            <div class="divRow">
                                <div class="divCell" >
                                    
                                </div>
                                <div class="divCell" >
                                    
                                </div>
                            </div>
                        </div>
                    
                    </div>
                    <div <?php echo $varObj->makeTabDivClass("values");?> id="values">
                        <h4>Get the Value List</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow" style="background-color:#f7f7f7;">
                                <div class="divCell" style="width:40%;">
                                    <h6>Search for a value</h6>
                                    <form class="form-search">
                                        <div class="input-append">
                                            <input class="span2" id="valLook" type="text" />
                                            <input type="hidden" name="varUUID" id="valsVarUUID" value="<?php echo $varObj->varUUID; ?>" />
                                            <button class="btn" type="button" onclick="valsLookUp();">Find</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell" style="width:60%;">
                                    <h6>Use Property to Assign Chronology to Associated Items</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/chrono-tag-by-prop">
                                        <div class="control-group">
                                            <label class="control-label" for="chronoPropUUID">Property UUID</label>
                                            <div class="controls">
                                                <input name="propUUID" type="text" class="input-large" id="chronoPropUUID" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="chronoPropVal">Property Value</label>
                                            <div class="controls">
                                                <input name="propVal" type="text" class="input-large" id="chronoPropVal" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="tStart">Start Time</label>
                                            <div class="controls">
                                                <input name="tStart" type="text" class="input-large" id="tStart" placeholder="(Start time)" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="tEnd">End Time</label>
                                            <div class="controls">
                                                <input name="tEnd" type="text" class="input-large" id="tEnd" placeholder="(End time)" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Assign Chronology</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="divRow" style="background-color:#f7f7f7;">
                                <div class="divCell" style="width:40%;">
                                   
                                </div>
                                <div class="divCell" style="width:60%;">
                                    <h6>Use Property to Link Items</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/create-links-by-property">
                                        <div class="control-group">
                                            <label class="control-label" for="LinkPropUUID">Property UUID</label>
                                            <div class="controls">
                                                <input name="propUUID" type="text" class="input-large" id="LinkPropUUID" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="LinkPropVal">Property Value</label>
                                            <div class="controls">
                                                <input name="propVal" type="text" class="input-large" id="LinkPropVal" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="LinkNewProjUUID">Project UUID</label>
                                            <div class="controls">
                                                <input name="projUUID" type="text" size="80" style="font-size:70%;" id="LinkNewProjUUID" value="<?php echo $varObj->projectUUID; ?>" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label">New Linked Item Origin or Target of Relationship</label>
                                            <div class="controls">
                                                <label class="radio">
                                                    Target
                                                    <input type="radio" name="linkedItemPosition" value="target" checked="true" />
                                                </label>
                                                <label class="radio">
                                                    Origin
                                                    <input type="radio" name="linkedItemPosition" value="origin" />
                                                </label>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label">New Linked Item Type</label>
                                            <div class="controls">
                                                <label class="radio">
                                                    Subject
                                                    <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="subject" checked="true" />
                                                </label>
                                                <label class="radio">
                                                    Media
                                                    <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="media" />
                                                </label>
                                                <label class="radio">
                                                    Document
                                                    <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="document" />
                                                </label>
                                                <label class="radio">
                                                    Project
                                                    <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="project" />
                                                </label>
                                                <label class="radio">
                                                    Person
                                                    <input onchange="javascript:updateLinkedItemType('newLink');" type="radio" name="newLinkLinkedType" value="person" />
                                                </label>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="LinkNewLinkedItemType">New Link Item Type (from above)</label>
                                            <div class="controls">
                                                <input name="linkedItemType" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedItemType" value="subject" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="LinkNewLinkedUUID">New Link Item UUID<br/><div id="newLinkLinkedItemData"></div></label>
                                            <div class="controls">
                                                <input onchange="javascript:getLinkingItemData('newLink');" name="linkedUUID" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedUUID" value="" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="LinkNewLinkedRelType">New Link Relation Type</label>
                                            <div class="controls">
                                                <input name="linkType" type="text" size="80" style="font-size:70%;" id="LinkNewLinkedRelType" value="link" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="PersonNewSubmit">Create New Link</label>
                                            <div class="controls">
                                                <button id="LinkNewSubmit" class="btn btn-inverse" type="submit" title="Create the new link">Create Link!</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div id="vals" style="padding-top:10%;padding-left:5%;padding-right:5%; background-color: white;">
                                    
                        </div>
                    </div>
        
                    <div <?php echo $varObj->makeTabDivClass("unit-types");?> id="unit-types">
                        <h4>Get the Value List</h4>
                        <div class="divTab" style="width:100%;">
                            <div class="divRow" style="background-color:#f7f7f7;">
                                <div class="divCell" style="width:40%;">
                                    <h6>Search for a value</h6>
                                    <form class="form-search">
                                        <div class="input-append">
                                            <input class="span2" id="valLook" type="text" />
                                            <input type="hidden" name="varUUID" id="valsVarUUID" value="<?php echo $varObj->varUUID; ?>" />
                                            <button class="btn" type="button" onclick="valsLookUp();">Find</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="divCell" style="width:60%;">
                                    <h6>Use Property to Assign Chronology to Associated Items</h6>
                                    <form class="form-horizontal" method="post" action="../editorial/chrono-tag-by-prop">
                                        <div class="control-group">
                                            <label class="control-label" for="chronoPropUUID">Property UUID</label>
                                            <div class="controls">
                                                <input name="propUUID" type="text" class="input-large" id="chronoPropUUID" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="chronoPropVal">Property Value</label>
                                            <div class="controls">
                                                <input name="propVal" type="text" class="input-large" id="chronoPropVal" />
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="tStart">Start Time</label>
                                            <div class="controls">
                                                <input name="tStart" type="text" class="input-large" id="tStart" placeholder="(Start time)" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="tEnd">End Time</label>
                                            <div class="controls">
                                                <input name="tEnd" type="text" class="input-large" id="tEnd" placeholder="(End time)" >
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <div class="controls">
                                                <button type="submit" class="btn">Assign Chronology</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div id="vals" style="padding-top:10%;padding-left:5%;padding-right:5%; background-color: white;">
                                    
                        </div>
                    </div>
                    <div <?php echo $varObj->makeTabDivClass("linked-data");?> id="linked-data">
                        <h4>Linked Data for the Variable</h4>
                        <div>
                            <table class="table table-striped table-condensed table-hover table-bordered data-tab">
                                <thead>
                                    <tr>
                                        <th>Add/Delete</th>
                                        <th>Linked Type</th>
                                        <th>Linked URI</th>
                                        <th>Linked Label</th>
                                        <th>Vocabulary</th>
                                        <th>Vocab URI</th>
                                    </tr>
                                </thead>
                                <tbody id="linked-data-var">
                            <?php
                            if(is_array($varObj->varLinks)){
                                foreach($varObj->varLinks as $row){
                                ?>
                                    <tr>
                                        <td><form><button type="submit" class="btn btn-warning btn-mini">X</button></form></td>
                                        <td><?php echo $row["linkedType"]; ?></td>
                                        <td><p><small><?php echo $row["linkedURI"]; ?></small></p></td>
                                        <td><?php echo $row["linkedLabel"]; ?></td>
                                        <td><?php echo $row["vocabulary"]; ?></td>
                                        <td><p><small><?php echo $row["vocabURI"]; ?></small></p></td>
                                    </tr>
                            
                            <?php 
                                }//end loop through links
                            }//end case with links
                            ?>
                                <form>
                                    <tr>
                                        <td><button type="submit" class="btn btn-inverse btn-mini">Add</button></form></td>
                                        <td><?php echo $row["linkedType"]; ?></td>
                                        <td><p><small><?php echo $row["linkedURI"]; ?></small></p></td>
                                        <td><?php echo $row["linkedLabel"]; ?></td>
                                        <td><?php echo $row["vocabulary"]; ?></td>
                                        <td><p><small><?php echo $row["vocabURI"]; ?></small></p></td>
                                    </tr>
                                </form>
                                </tbody>
                            </table>
                        </div>
                        <div>
                            <table class="table table-striped table-condensed table-hover table-bordered data-tab">
                                <thead>
                                    <tr>
                                        <th>Property UUID</th>
                                        <th>Value</th>
                                        <th>Linked URI</th>
                                        <th>Linked Label</th>
                                        <th>Vocabulary</th>
                                        <th>Vocab URI</th>
                                    </tr>
                                </thead>
                                <tbody id="linked-data-vals">
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                   
                <script>
                    
                    function getParameterByName(name) {
                        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
                        var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                            results = regex.exec(location.search);
                        return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
                    }
                    
                    var selTab = getParameterByName("tab");
                    
                    if(selTab){
                        $(function () {
                            e.preventDefault();
                            $('#myTab a[href="#' + selTab + '"]').tab('show'); // Select tab by name
                        });
                    }
                    else{
                        $(function () {
                            $('#myTab a:first').tab('show');
                        });
                    }
                    
                    <?php
                    if(isset($requestParams["tab"])){
                    ?>    
                        
                    
                    <?php   
                    }//end case with a tab to select
                    ?>
                    
                  </script>
                
                
            </div>
        </div>
    </body>
</html>