<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<table>
    <tr>
        <th>Browse to file</th>
        <td><input type="file" /></td>
    </tr>
</table>
<?php echo $this->escape($this->testVar); ?>

<div class="dijitFileInput">
	<input id="${id}" class="dijitFileInputReal" type="file" dojoAttachPoint="fileInput" name="${name}" />
	<div class="dijitFakeInput">
		<input class="dijitFileInputVisible" type="text" dojoAttachPoint="focusNode, inputNode" />
		<div class="dijitInline dijitFileInputText" dojoAttachPoint="titleNode">${label}</div>
		<div class="dijitInline dijitFileInputButton" dojoAttachPoint="cancelNode" 
			dojoAttachEvent="onclick:reset">${cancelText}</div>
	</div>
</div>

<?php echo $this->render('footer.phtml'); ?>