<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <link id="themeStyles" rel="stylesheet" href="/public/scripts/dojoroot/dijit/themes/tundra/tundra.css">
        <style type="text/css">
            @import "/public/styles/importer.css";         
            @import "/public/styles/navigation.css";               
        </style>        

    </head>
    <body class="tundra">
        <br />  
        
        <table class="mainTable" align="center">
        <tr>
            <td colspan="2" class="headerCell">
                <?php echo $this->header; ?>
                <div id="errorMessage"></div>
            </td>
        </tr>
        <tr>
            <td class="navCell">&nbsp;</td>
            <td class="contentCell" id="contentCell">
                <h2><?php echo $this->title; ?></h2>
                <?php if(!empty($this->message)) :?>
                    <div id="message">
                    <?php echo $this->escape($this->message);?>
                    </div>
                <?php endif; ?>
                
                <form action="<?php echo $this->baseUrl ?>/auth/login" method="post">
                    <div>
                        <label for="username">Username</label>
                        <input type="text" name="username" value=""/>
                    </div>
                    <div>
                        <label for="password">Password</label>
                        <input type="password" name="password" value=""/>
                    </div>
                    <div id="formbutton">
                    <input type="submit" name="login" value="Login" />
                    </div>
                </form>    
            </td>
        </tr>
        <tr>
            <td colspan="2" class="footerCell">
                <?php echo $this->footer; ?>
            </td>
        </tr>
    </table>
    </body>    
</html>

