<?php

$tablePubObj = $this->tablePubObj;

?>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Table Publishing Index</title>
        <link href="../public/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/bootstrap-responsive.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-general.css"  rel="stylesheet" type="text/css" />
        
    </head>
    <body>
        <div id="main">
            <div id="main_content">
                
                <h2>Output Tables (<?php echo count($tablePubObj->tables); ?>)</h2>
                <table class="table table-striped table-condensed table-hover table-bordered data-tab" id="sample" >
                    <thead>
                        <tr>
                            <th>Table ID</th>
                            <th>Number of Fields</th>
                            <th>Table Name</th>
                            <th>Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    <?php 
                    $i = 1;
                    foreach($tablePubObj->tables as $row){
                    ?>
                        <tr id="<?php echo "rec-".$i;?>" >
                            <td><a href="../table/publish?table=<?php echo $row["source_id"]; ?>"><?php echo $row["source_id"]; ?></a></td>
                            <td><?php echo $row["fieldCount"]; ?></td>
                            <td><?php echo $row["title"]; ?></td>
                            <td><?php echo $row["updated"]; ?></td>
                        </tr>
                    <?php
                        $i++;
                    }//end loop through the table array 
                    ?>
                
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>