<?php

$tablePubObj = $this->tablePubObj;

?>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Table Publishing</title>
        <link href="../public/css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/bootstrap-responsive.css"  rel="stylesheet" type="text/css" />
        <link href="../public/css/rev2-general.css"  rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="main">
            <div id="main_content">
                <h2>Table Preview</h2>
                <table class="table table-striped table-condensed table-hover table-bordered data-tab" >
                    <thead>
                        <tr>
                        <?php
                        foreach($tablePubObj->tableFieldsTemp as $fieldKey => $fieldLabel){
                                
                        ?>        
                            <th><?php echo $fieldLabel; ?></th>
                         <?php   
                        }//end loop through the table array  
                        ?>
                        </tr>
                    </thead>
                    <tbody>
                        
                    <?php 
                    $i = 1;
                    foreach($tablePubObj->sampleRecords as $row){
                    ?>
                        <tr id="<?php echo "rec-".$i;?>" >
                            
                        <?php
                        foreach($row as $fieldKey => $value){
                            if(array_key_exists($fieldKey, $tablePubObj->tableFieldsTemp)){ 
                        ?> 
                            <td><?php echo $value; ?></td>
                        <?php     
                            }//end case with field key existing
                        }//end loop through the fields and values
                        ?>
                        </tr>
                    <?php
                        $i++;
                    }//end loop through the table array 
                    ?>
                
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>