<?php

$tablePublish = $this->tablePublish;

?>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Table Publishing</title>
        <link href="../css/bootstrap.css"  rel="stylesheet" type="text/css" />
        <link href="../css/bootstrap-responsive.css"  rel="stylesheet" type="text/css" />
    </head>
    <body>
        <table>
            <thead>
                <tr>
                <?php
                foreach($tableArray as $recordkey => $fieldVals){
                        
                        ?>
                        <th>Record URI</th>
                        <?php
                        foreach($fieldVals as $fieldKey => $value){
                        ?> 
                            <th><?php echo $fieldKey; ?></th>
                        <?php     
                        }//end loop through the fields and values
                    break; //no need to do the whole array, we're setting up the heading
                }//end loop through the table array  
                ?>
                </tr>
            </thead>
            <tbody>
                
            <?php 
            $i = 1;
            foreach($tableArray as $recordkey => $fieldVals){
            ?>
                <tr id="<?php echo "rec-".$i;?>" >
                    <td><?php echo $recordkey; ?></td>
                    <?php
                    foreach($fieldVals as $fieldKey => $value){
                    ?> 
                    <td><?php echo $value; ?></td>
                    <?php     
                    }//end loop through the fields and values
                    ?>
                </tr>
            <?php
                $i++;
            }//end loop through the table array 
            ?>
        
            </tbody>
        </table>
    </body>
</html>