<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <link id="themeStyles" rel="stylesheet" href="/public/scripts/dojoroot/dijit/themes/tundra/tundra.css">
        <style type="text/css">
            @import "/public/scripts/dojoroot/dojo/resources/dojo.css";
            @import "/public/scripts/dojoroot/dojox/grid/resources/tundraGrid.css";
            @import "/public/scripts/dojoroot/dojox/layout/resources/FloatingPane.css";
            @import "/public/styles/importer.css";         
            @import "/public/styles/navigation.css";               
        </style>        
        <script type="text/javascript" src="/public/scripts/json2.js"></script>
        <script type="text/javascript" src="/public/scripts/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/dojoroot/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
        <script type="text/javascript" src="/public/scripts/prototype-1.6.0.2.js"></script>
        
        <!-- custom application-level script files -->
        <script type="text/javascript" src="/public/scripts/application/importer/wizard.js"></script>
        <script type="text/javascript" src="/public/scripts/application/browserDetect.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/navigation.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/user.js"></script>
        
        <script type="text/javascript">        
            dojo.require("dojo.parser");
            dojo.require("dojo.data.ItemFileWriteStore");
            dojo.require("dojox.grid.DataGrid");
            dojo.require("dojox.grid.cells");
            dojo.require("dijit.Dialog");
            dojo.require("dijit.form.TextBox");
            dojo.require("dijit.form.Button");
            dojo.require("dojox.layout.FloatingPane");
            
            //added to make the radiobuttons:
            dojo.require("dijit.form.CheckBox");
            
            dojo.require("dijit.form.FilteringSelect");
            dojo.require("dojox.form.DropDownSelect");
            
            <?php echo $this->state; ?>
                       
            //include all of the functions that need to be called on startup:
            dojo.addOnLoad(function()
            {
                displayState();
                initUsersPane();
                
                //hide initialization HTML until importer has completely loaded:
                dojo.byId('loaderInner').innerHTML += " done.";
                setTimeout(function hideLoader(){
                        var loader = dojo.byId('loader'); 
                        dojo.fadeOut({ node: loader, duration:500,
                                onEnd: function(){ 
                                        loader.style.display = "none"; 
                                }
                        }).play();
                }, 250);
            });
        </script>
    
    </head>
    <body class="tundra">
        <div id="loader"><div id="loaderInner">Loading Importer ... </div></div>
        <br />  
        
        <div>
            Name: <strong><span id="spanUserName"></span></strong><br />
            Project Selected: <strong><span id="spanProjectSelected"></span></strong> 
        </div>
        <table class="mainTable" align="center">
        <tr>
            <td colspan="2" class="headerCell">
                <?php echo $this->header; ?>
                <div id="errorMessage"></div>
            </td>
        </tr>
        <tr>
            <td class="navCell">
                <?php echo $this->sidebar; ?>
            </td>
            <td class="contentCell" id="contentCell">
                <?php echo $this->partial("wizardHeader.phtml") ?>
                
                <table style="width: 100%;" align="center">
                    <tr>
                        <td>                            
                            <div style="padding-top: 5px; padding-bottom: 10px; vertical-align: baseline">
                                <span class="circleNumber">1</span>
                                <span class="instructionsShort">Select a user</span>
                                <div style="padding-top: 3px; padding-left: 30px;">
                                    <input id="ddUsers"> 
                                    <a href="javascript:dijit.byId('dialogAddUser').show();">create new</a>
                                </div>
                            </div>
                                                         
                            <div style="padding: 0 0 5px 0px;">
                                <span class="circleNumber">2</span>
                                <span class="instructionsShort">Select a role</span>
                                <div style="padding-top: 3px; padding-left: 30px;">
                                    
                                    <input id="ddRoles"><br />
                                    <input type="checkbox" id="linkAll" name="linkAll" /> Link to all<br />
                                    <em>
                                    (Unchecking will link this person to descriptions only if no other
                                    author / observer is indicated)
                                    </em>
                                </div>
                            </div>
                            
                            <span class="circleNumber">3</span>
                                <span class="instructionsShort">Save</span>
                                <div style="padding-left: 30px;">
                                    <button dojoType="dijit.form.Button" onclick="attachUser();">Update Table Responsibility</button>
                                </div>
                        </td>
                        <td>                       
                            <div class="frame" style="height:350px;width:360px;">
                                <div class="frameHeader" style="height:22px;">Person responsible for this table(s)</div>
                                <div  style="height:250px;width:350px;" id="gridUserRoleTableCell" ></div>   
                            </div>
                        </td>
                    </tr>
                </table>
                
                <!-- Add New User -->
                <div dojoType="dijit.Dialog" id="dialogAddUser" title="Add a New User">
                    <table border="0" cellspacing="0" cellpadding="2" class="tblGeneric">
                        <tr>
                            <td width="149">Given Name:</td>
                            <td><input id="f_f_name" name="f_name" type="text" value="First" size="50" maxlength="98" onchange="comp_names()"/></td>
                        </tr>
                        <tr>
                            <td>Middle Initial:</td>
                            <td><input id="f_m_initial" name="m_inital" type="text" value="" size="2" maxlength="2" onchange="comp_names()"/></td>
                        </tr>
                        <tr>
                            <td>Family Name (surname):</td>
                            <td><input id="f_l_name" name="l_name" type="text" value="Surname" size="50" maxlength="100" onchange="comp_names()"/></td>
                        </tr>
                        <tr>
                            <td>Initials</td>
                            <td><input id="f_initals" name="initals" type="text" value="" size="5" maxlength="5" /></td>
                        </tr>
                        <tr>
                            <td>Full Name </td>
                            <td><input id="f_combined_name" name="combined_name" type="text" value="First MI. Surname" size="50" maxlength="100" /></td>
                        </tr>
                        <tr>
                            <td>Email: </td>
                            <td><input id="f_email" name="email" type="text" value="you@anywhere.edu" size="50" maxlength="200" /></td>
                        </tr>
                        <tr>
                            <td>Affiliation:</td>
                            <td>
                                <input id="ddAffiliations" />
                                <!-- input id="f_affil" name="affil" type="text" value="Your organization" size="50" maxlength="200" / -->
                            </td>
                        </tr>
                        <tr class="tblGenericRowOdd">
                            <td colspan="2" align="center">
                                <button dojoType="dijit.form.Button" onclick="addUser();">Add</button> 
                                <button dojoType="dijit.form.Button" onclick="dijit.byId('dialogAddUser').hide();">Cancel</button>
                            </td>
                        </tr>
                    </table>
                </div>
                
            </td>
        </tr>
        <tr>
            <td colspan="2" class="footerCell">
                <?php echo $this->footer; ?>
            </td>
        </tr>
    </table>
    </body>    
</html>
