<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title><!-- Insert your title here --></title>
    <script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/dojoroot/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
    <script type="text/javascript">        
        dojo.require("dojo.parser");
        dojo.require("dijit.layout.ContentPane");
        dojo.require("dijit.layout.TabContainer");
    </script>  
    <script>
        <script type="text/javascript"> 
            dojo.registerModulePath('nickel', '/scripts/nickel'); 
            dojo.require('nickel.rpc.book'); 
            dojo.addOnLoad(function()
                { 
                    nickel.rpc.book.simpleEcho().addCallback(
                        function(msg){ 
                            alert(msg); //Alert: Hello World 
                        }
                    ); 
                    nickel.rpc.book.getTitle(1).addCallback(
                        function(title)
                        { 
                            alert(title); //Alert: title of book with ID 1 in database 
                        }
                    ); 
                    nickel.rpc.book.setTitle(1, 'Foo').addCallback(
                        function(result)
                        { 
                            alert('success'); //Sets the title of book with ID 1 to 'Foo' 
                        }
                    ); 
                }
            ); 
            </script>
    </script>
</head>
<body>
    <!-- Insert your content here -->
</body>
</html>
