<html>
    <head>
        <title><?php echo $this->title; ?></title>
        <link id="themeStyles" rel="stylesheet" href="/public/scripts/dojoroot/dijit/themes/tundra/tundra.css">
        <style type="text/css">
            @import "/public/scripts/dojoroot/dojo/resources/dojo.css";
            @import "/public/scripts/dojoroot/dojox/grid/resources/tundraGrid.css";
            @import "/public/scripts/dojoroot/dojox/layout/resources/FloatingPane.css";
            @import "/public/styles/importer.css";         
            @import "/public/styles/navigation.css";               
        </style>        
        <script type="text/javascript" src="/public/scripts/json2.js"></script>
        <script type="text/javascript" src="/public/scripts/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/dojoroot/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
        <script type="text/javascript" src="/public/scripts/prototype-1.6.0.2.js"></script>
        
        <!-- custom application-level script files -->
        <script type="text/javascript" src="/public/scripts/application/importer/wizard.js"></script>
        <script type="text/javascript" src="/public/scripts/application/browserDetect.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/utils.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/navigation.js"></script>
        <script type="text/javascript" src="/public/scripts/application/importer/relationships.js"></script>
        
        <script type="text/javascript">        
            dojo.require("dojo.parser");
            dojo.require("dojo.data.ItemFileWriteStore");
            dojo.require("dojox.grid.DataGrid");
            dojo.require("dojox.grid.cells");
            dojo.require("dijit.Dialog");
            dojo.require("dijit.form.TextBox");
            dojo.require("dijit.form.Button");
            dojo.require("dojox.layout.FloatingPane");            
            dojo.require("dijit.TitlePane");
            dojo.require("dijit.Tree");
            
            dojo.require("dijit.form.ComboBox");
            dojo.require("dijit.form.FilteringSelect");
            dojo.require("dojox.form.DropDownSelect");
            
            
            <?php echo $this->state; ?>
                       
            //include all of the functions that need to be called on startup:
            dojo.addOnLoad(function()
            {
                initRelationshipsPane();
                
                //hide initialization HTML until importer has completely loaded:
                dojo.byId('loaderInner').innerHTML += " done.";
                setTimeout(function hideLoader(){
                        var loader = dojo.byId('loader'); 
                        dojo.fadeOut({ node: loader, duration:500,
                                onEnd: function(){ 
                                        loader.style.display = "none"; 
                                }
                        }).play();
                }, 250);
            });
        </script>
    
    </head>
    <body class="tundra">
        <div id="loader"><div id="loaderInner">Loading Importer ... </div></div>
        <br />  
        
        <div>
            Name: <strong><span id="spanUserName"></span></strong><br />
            Project Selected: <strong><span id="spanProjectSelected"></span></strong> 
        </div>
        <table class="mainTable" align="center">
        <tr>
            <td colspan="2" class="headerCell">
                <?php echo $this->header; ?>
                <div id="errorMessage"></div>
            </td>
        </tr>
        <tr>
            <td class="navCell">
                <?php echo $this->sidebar; ?>
            </td>
            <td class="contentCell" id="contentCell">
                <?php echo $this->partial("wizardHeader.phtml") ?>
                
                <div id="testTreeDiv"></div>
                <table cellpadding="0" cellspacing="5" width="100%" align="center">
                    <tr>
                        <td style="width: 385px;" class="borderDotted">
                            <strong>Relationships</strong>
                        </td>
                        <td class="borderDotted">
                            <strong>Sample Data</strong>
                        </td>
                    </tr>
                    <tr>
                        <!-- td id="gridLinkObjectsContainer" style="width: 102px; height: 330px; border-right: dotted 1px #CCC; border-bottom: dotted 1px #CCC;">
                        </td -->
                        <td style="width: 385px;"  class="borderDotted">
                            <div id="relationshipsCell" style="width: 385px;height:300px;"></div>
                            <div class="buttonPane" style="width: 385px;">
                                <button dojoType="dijit.form.Button"
                                        onclick="initAddRelationshipDialog('containment')">
                                    Add Containment Link
                                </button>
                                <button dojoType="dijit.form.Button"
                                        onclick="initAddRelationshipDialog('link')">
                                    Add Custom Link
                                </button>
                                <button jsID="fieldLinksButton" dojoType="dijit.form.Button"
                                        onclick="initAddRelationshipDialog('db')">
                                    Add Field Link
                                </button>
                            </div>
                        </td>
                        <td class="borderDotted">
                            <div style="height: 330px; overflow:auto;">
                                <div id="treeContainerCell"></div>
                                <div id="otherRelationshipsContainerCell"></div>
                            </div>
                        </td>
                    </tr>
                </table>
                
                <!-- Add New Project Dialog Box-->                        
                <div dojoType="dijit.Dialog" id="dialogAddRelationship" title="Add a Relationship">
                    <table style="width: 600px;">
                        <tr>
                            <th><label for="ddOrigin">1. Select the Origin</label></th>
                            <th><label for="ddRelationship">2. Select the Relationship</label></th>
                            <th><label for="ddTarget">3. Select the Target</label></th>
                        </tr>
                        <tr>
                            <td><input id="ddOrigin"></td>
                            <td><input id="ddRelationship"></td>
                            <td id="ddTargetCell"><input id="ddTarget"></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <button dojoType="dijit.form.Button" onclick="addRelationship();">Add</button>
                                <button dojoType="dijit.form.Button" onclick="dijit.byId('dialogAddRelationship').hide()">Cancel</button> 
                            </td>
                        </tr>
                    </table>                            
                </div>

                <!-- Remove Relationship Dialog Box -->
                <div dojoType="dijit.Dialog" id="dialogRemoveRelationship" title="Remove Relationship From Dataset"
                    execute="removeRelationship();">
                    <div></div>
                    <table>
                        <caption id="removeRelationshipText">
                            Are you sure you want to remove this project and it's corresponding data from
                            the system?
                        </caption>            
                        <tr>
                            <td colspan="2">
                                <button dojoType="dijit.form.Button" type="submit">Remove</button>
                                <button dojoType="dijit.form.Button" onclick="dijit.byId('dialogRemoveRelationship').hide()">Cancel</button> 
                            </td>
                        </tr>
                    </table>
                </div>
                
            </td>
        </tr>
        <tr>
            <td colspan="2" class="footerCell">
                <?php echo $this->footer; ?>
            </td>
        </tr>
    </table>
    </body>   
</html>
